# -*- coding: utf-8 -*-

{
    'name': "Employee Travel and Travel Expense Management",
    'currency': 'EUR',
    'license': 'Other proprietary',
    'price': 0.0,
    'summary': """This module allow you to manage travel of your employees.""",
    'description': """ """,
    'author': "TechUltra Solutions Pvt. Ltd.",
    'website': "https://www.techultrasolutions.com/",
    'support': 'techultrasolutions.com',
    'version': '1.0.6',
    'category': 'Human Resources',
    'images': [],
    'depends': ['security_groups', 'hr', 'approvals', 'hr_core', 'hr_expense', 'hr_approvals', 'project',
                'hr_expense_custom'],
    'live_test_url': 'https://www.techultrasolutions.com/',
    'data': ['data/ir_sequence_data.xml',
             'data/mail_activity_data.xml',
             'data/travel_agency_mail_template.xml',
             'data/approval_category_data.xml',
             'data/expense_product_data.xml',
             'security/ir.model.access.csv',
             'security/travel_security.xml',
             'views/res_partner_view.xml',
             'views/travel_reject_reason_view.xml',
             'views/travel_request_view.xml',
             'views/travel_cost_center_line_view.xml',
             'views/travel_request_settings_view.xml',
             'views/travel_request_quotation_view.xml',
             'views/request_modify_reason_wizard_view.xml',
             'views/perdiem_rule_view.xml',
             'views/approval_category_view.xml',
             'reports/reports.xml',
             'reports/custom_layout.xml',
             'reports/travel_ticket_request_template.xml',
             ],
    'installable': True,
    'application': False,
}
