# -*- coding: utf-8 -*-

{
    'name': 'Report Request',
    'description': 'Employee Report Request ',
    'version': '1.1.15',
    'summary': 'Report Request for the Bank and  To Whom It May Concern and employment later and  Immigration Letter',
    'license': 'OPL-1',
    'author': 'TechUltra Solutions Pvt. Ltd.',
    'website': 'https://www.techultrasolutions.com/',
    'images': [],
    'category': 'uncategorized',
    'description': """ Report Request for the Bank and  To Whom It May Concern and employment later and  Immigration Letter""",
    'depends': ['approvals', 'res_company_custom', 'base', 'security_groups', 'hr_employee_custom', 'contacts',
                'employee_bank_approvals'],
    'data': ['security/ir.model.access.csv',
             'data/ir_sequence_data.xml',
             'data/ir_rule.xml',
             'data/embassy_demo.xml',
             'data/other_entities_demo.xml',
             'data/approval_category_data.xml',
             'views/report_request_view.xml',
             'views/res_bank_view.xml',
             'views/res_embassy_view.xml',
             'views/hr_employee_view.xml',
             'views/res_other_entities_view.xml',
             'views/responsible_report_person_view.xml',
             'views/res_config_view.xml',
             'views/approval_category_view.xml',
             'reports/employment_letter_template.xml',
             'reports/bank_report_template.xml',
             'reports/to_whom_it_may_concern_template.xml',
             'reports/immigration_letter_template.xml',
             'reports/report.xml'],
    'auto_install': False,
}
