# -*- coding: utf-8 -*-

{
    'name': 'Child Education',
    'description': 'Child Education',
    'version': '1.1.2',
    'summary': 'Child Education Request user can calm for the education amount for the child',
    'license': 'OPL-1',
    'author': 'TechUltra Solutions Pvt. Ltd.',
    'website': 'https://www.techultrasolutions.com/',
    'images': [],
    'category': 'uncategorized',
    'description': """ Child Education Request user can calm for the education amount for the child""",
    'depends': ['hr_employee_custom', 'hr_contract_custom', 'hr_payroll', 'schools', 'security_groups', 'hr_approvals',
                'approvals'],
    'data': ['data/ir_sequence_data.xml',
             'data/ir_mail_activity.xml',
             'data/approval_category_data.xml',
             'security/ir.model.access.csv',
             'views/education_eligibility_view.xml',
             'views/education_academic_year_view.xml',
             'views/education_reject_reason_view.xml',
             'views/education_request_view.xml',
             'views/education_request_line_view.xml',
             'views/education_request_settings_view.xml',
             'views/education_terms_fees_view.xml',
             'views/approval_category_view.xml',
             'report/reports.xml',
             'report/education_claim_report.xml'],
    'auto_install': False,
}
